name: Alphavantage Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ALPHAVANTAGE_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
    - 'alphavantage-server/**'
    - '.github/workflows/alphavantage-production.yaml'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: Production â€“ alphavantage
    env:
      working-directory: ./alphavantage-server

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@33.2.0
        working-directory: ${{env.working-directory}}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Build Project Artifacts
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Deploy Project Artifacts to Vercel
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}
        